---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: redis-ws-sample
  name: redis-ws-sample
spec:
  type: ClusterIP
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    app: redis-ws-sample
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: redis-ws-sample
  name: redis-ws-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-ws-sample
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis-ws-sample
    spec:
      containers:
        - image: redis:6.2-alpine
          name: redis-ws-sample
          ports:
            - containerPort: 6379
          resources: {}
      restartPolicy: Always
status: {}